/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorEducationRouteImport } from './routes/sponsor-education'
import { Route as OrphanageRouteImport } from './routes/orphanage'
import { Route as OldAgeHomeRouteImport } from './routes/old-age-home'
import { Route as GroceriesRouteImport } from './routes/groceries'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CrecheRouteImport } from './routes/creche'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeneficiariesIdRouteImport } from './routes/beneficiaries.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicSeedKnowledgeRouteImport } from './routes/api/public/seed-knowledge'

const SponsorEducationRoute = SponsorEducationRouteImport.update({
  id: '/sponsor-education',
  path: '/sponsor-education',
  getParentRoute: () => rootRouteImport,
} as any)
const OrphanageRoute = OrphanageRouteImport.update({
  id: '/orphanage',
  path: '/orphanage',
  getParentRoute: () => rootRouteImport,
} as any)
const OldAgeHomeRoute = OldAgeHomeRouteImport.update({
  id: '/old-age-home',
  path: '/old-age-home',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceriesRoute = GroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CrecheRoute = CrecheRouteImport.update({
  id: '/creche',
  path: '/creche',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesIdRoute = BeneficiariesIdRouteImport.update({
  id: '/beneficiaries/$id',
  path: '/beneficiaries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedKnowledgeRoute = ApiPublicSeedKnowledgeRouteImport.update({
  id: '/api/public/seed-knowledge',
  path: '/api/public/seed-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creche': typeof CrecheRoute
  '/donate': typeof DonateRoute
  '/groceries': typeof GroceriesRoute
  '/old-age-home': typeof OldAgeHomeRoute
  '/orphanage': typeof OrphanageRoute
  '/sponsor-education': typeof SponsorEducationRoute
  '/api/chat': typeof ApiChatRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creche': typeof CrecheRoute
  '/donate': typeof DonateRoute
  '/groceries': typeof GroceriesRoute
  '/old-age-home': typeof OldAgeHomeRoute
  '/orphanage': typeof OrphanageRoute
  '/sponsor-education': typeof SponsorEducationRoute
  '/api/chat': typeof ApiChatRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creche': typeof CrecheRoute
  '/donate': typeof DonateRoute
  '/groceries': typeof GroceriesRoute
  '/old-age-home': typeof OldAgeHomeRoute
  '/orphanage': typeof OrphanageRoute
  '/sponsor-education': typeof SponsorEducationRoute
  '/api/chat': typeof ApiChatRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRoute
  '/api/public/seed-knowledge': typeof ApiPublicSeedKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/creche'
    | '/donate'
    | '/groceries'
    | '/old-age-home'
    | '/orphanage'
    | '/sponsor-education'
    | '/api/chat'
    | '/beneficiaries/$id'
    | '/api/public/seed-knowledge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/creche'
    | '/donate'
    | '/groceries'
    | '/old-age-home'
    | '/orphanage'
    | '/sponsor-education'
    | '/api/chat'
    | '/beneficiaries/$id'
    | '/api/public/seed-knowledge'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/creche'
    | '/donate'
    | '/groceries'
    | '/old-age-home'
    | '/orphanage'
    | '/sponsor-education'
    | '/api/chat'
    | '/beneficiaries/$id'
    | '/api/public/seed-knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CrecheRoute: typeof CrecheRoute
  DonateRoute: typeof DonateRoute
  GroceriesRoute: typeof GroceriesRoute
  OldAgeHomeRoute: typeof OldAgeHomeRoute
  OrphanageRoute: typeof OrphanageRoute
  SponsorEducationRoute: typeof SponsorEducationRoute
  ApiChatRoute: typeof ApiChatRoute
  BeneficiariesIdRoute: typeof BeneficiariesIdRoute
  ApiPublicSeedKnowledgeRoute: typeof ApiPublicSeedKnowledgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsor-education': {
      id: '/sponsor-education'
      path: '/sponsor-education'
      fullPath: '/sponsor-education'
      preLoaderRoute: typeof SponsorEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orphanage': {
      id: '/orphanage'
      path: '/orphanage'
      fullPath: '/orphanage'
      preLoaderRoute: typeof OrphanageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old-age-home': {
      id: '/old-age-home'
      path: '/old-age-home'
      fullPath: '/old-age-home'
      preLoaderRoute: typeof OldAgeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groceries': {
      id: '/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof GroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creche': {
      id: '/creche'
      path: '/creche'
      fullPath: '/creche'
      preLoaderRoute: typeof CrecheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries/$id': {
      id: '/beneficiaries/$id'
      path: '/beneficiaries/$id'
      fullPath: '/beneficiaries/$id'
      preLoaderRoute: typeof BeneficiariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-knowledge': {
      id: '/api/public/seed-knowledge'
      path: '/api/public/seed-knowledge'
      fullPath: '/api/public/seed-knowledge'
      preLoaderRoute: typeof ApiPublicSeedKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CrecheRoute: CrecheRoute,
  DonateRoute: DonateRoute,
  GroceriesRoute: GroceriesRoute,
  OldAgeHomeRoute: OldAgeHomeRoute,
  OrphanageRoute: OrphanageRoute,
  SponsorEducationRoute: SponsorEducationRoute,
  ApiChatRoute: ApiChatRoute,
  BeneficiariesIdRoute: BeneficiariesIdRoute,
  ApiPublicSeedKnowledgeRoute: ApiPublicSeedKnowledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
